/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProgressJobIdRouteImport } from './routes/progress.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressJobIdRoute = ProgressJobIdRouteImport.update({
  id: '/progress/$jobId',
  path: '/progress/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/new': typeof NewRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/new': typeof NewRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/new': typeof NewRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jobs' | '/new' | '/progress/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jobs' | '/new' | '/progress/$jobId'
  id: '__root__' | '/' | '/jobs' | '/new' | '/progress/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  NewRoute: typeof NewRoute
  ProgressJobIdRoute: typeof ProgressJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/$jobId': {
      id: '/progress/$jobId'
      path: '/progress/$jobId'
      fullPath: '/progress/$jobId'
      preLoaderRoute: typeof ProgressJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  NewRoute: NewRoute,
  ProgressJobIdRoute: ProgressJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
